version: '3'

services:
  peer1:
    build: eureka-server
    environment:
      SETTINGS: peer1
  peer2:
    build: eureka-server
    environment:
      SETTINGS: peer2
  activeMQ:
    image: rmohr/activemq:latest
    ports:
      - "8161:8161"
  #      - "61616:61616"
  # 8161 exposed to demonstrate the behaviour of the queue.
  # todo check if 61616 needs to be exposed at all

  # todo before running: ActiveMQ properties need to be changed from
  # spring.activemq.broker-url=failover://tcp://localhost:61616
  # spring.activemq.broker-url=failover://tcp://activeMQ:61616

  # todo before running: MongoDB properties need to be changed from
  # spring.data.mongodb.host=localhost
  # spring.data.mongodb.host=mongoDB

  mongoDB:
    image: mongo:latest
    ports:
      - "27017:27017"

  patient-info:
    depends_on:
      - mongoDB
    build: patient-info
    image: "patient-info:latest"

  results-discovery:
    depends_on:
      - activeMQ
      - patient-info
    build: results-discovery
    image: "results-discovery:latest"

  web-ui:
    depends_on:
      - patient-info
      - results-discovery
    build: web-ui
    image: "web-ui:latest"
    ports:
      - "8080:8080"   # port exposed so users can access the web-ui
