version: '3'

services:
  # Eureka servers
  eureka1:
    build: eureka-server
    environment:
      SETTINGS: eureka1
    ports:
      - "9001:8761"
  eureka2:
    build: eureka-server
    environment:
      SETTINGS: eureka2
    ports:
      - "9002:8761"

  # Services
  patient-info:
    build: patient-info
    depends_on:
      - eureka1
      - eureka2
#  contacts:
#    build: contacts
#    depends_on:
#      - eureka1
#      - eureka2
  results-discovery:
    build: results-discovery
    depends_on:
      - eureka1
      - eureka2
  contact-tracing-followup:
    build: contact-tracing-followup
    depends_on:
      - eureka1
      - eureka2
  web-ui:
    build: web-ui
    depends_on:
      - eureka1
      - eureka2
      - results-discovery
      - contact-tracing-followup
    ports:
      - "8080:8080"

# Misc (DBs, ActiveMQ)
