---
spring:
  profiles: default
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false


---
spring:
  profiles: peer1
server:
  port: 9001

eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/,http://peer3:9003/eureka/
  server:
    peer-node-read-timeout-ms: 60000


---
spring:
  profiles: peer2
server:
  port: 9002
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/,http://peer3:9003/eureka/
  server:
    peer-node-read-timeout-ms: 60000

---
spring:
  profiles: peer3
server:
  port: 9003
eureka:
  instance:
    hostname: peer3
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/,http://peer3:9003/eureka/
  server:
    peer-node-read-timeout-ms: 60000