---
spring:
  profiles: default
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false


---
spring:
  profiles: eureka1
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka2:8761/eureka/
  server:
    peer-node-read-timeout-ms: 60000
    peer-node-connect-timeout-ms: 60000

---
spring:
  profiles: eureka2
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: eureka2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/
  server:
    peer-node-read-timeout-ms: 60000
    peer-node-connect-timeout-ms: 60000
