---
spring:
  profiles: default
  application:
    name: contract-tracing-follow-up-service
---
spring:
  profiles: docker
  application:
    name: contract-tracing-follow-up-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8761/eureka/,http://peer3:8761/eureka/
